### ISSUE TITLE
Fitbounds/Plot hits freeze - race condition

### ISSUE THREAD

**Issue by melbourne2991** [Leaflet/Leaflet#3294]
Looks like there was a similar issue to what i'm experiencing that should have been fixed in 0.7.3 #2484.
Seems to be some kind of race condition as I can't reproduce when stepping through breakpoints. The map freezes completely and becomes unusable, it seems to occur randomly with no real consistent pattern except it never seems to happen on the first 1-2 tries, sometimes it works fine indefinitely (well for long enough that I thought it was pointless to continue). Still not 100% sure it's leaflet but I can't see anything else in my code that could be causing this

I have these three methods being called after a user places a search request:

```
					map.setHits(results.data.hits);
					map.plotHits();
					map.fitBoundsToHits();
```

The methods:

```

/**
 * Set hits for further manipulation
 * @param {Array} Array of ES hits
 * @param {Function} Callback
 * @returns {MapInstance}
 */
Map.prototype.setHits = function(hits, cb) {
	this.hits = hits;

	return this;
};

/**
 * Plots points to map instance
 * @param  {Array[ES hit]} Array of ES hits
 * @param  {Function} Callback
 * @returns {MapInstance}
 */
Map.prototype.plotHits = function(hits, cb) {
	var map = this,
		hits = hits || this.hits;

	_.remove(this.markers, function(marker) {
		map.mapObj.removeLayer(marker);
		return true;
	});

	this.markers = _.map(hits, function(hit, i) {
		return L.marker(map.__getPointFromHit(hit)).addTo(map.mapObj);
	});

	return this;
};

/**
 * Fits map bounds to hits
 * @param  {Array[ES hit]} Array of ES hits
 * @param  {Function} Callback
 * @returns {MapInstance}
 */
Map.prototype.fitBoundsToHits = function(hits, cb) {
	var map = this,
		pointArr = [],
		hits = hits || this.hits;

	_.forEach(hits, function(hit, i) {
		pointArr.push(map.__getPointFromHit(hit));
	});

	this.bounds = L.latLngBounds(pointArr);
	this.mapObj.fitBounds(this.bounds, {});

	return this;
};

```

EDIT: When I remove plotHits(), I can't seem to replicate the issue, looks like perhaps plotting markers and then fitting to bounds in quick succession might have something to do with it.

**Comment by perliedman** [comment]
I'd guess this is the issue you're seeing: #2021 - if you scroll to the end of the pretty long discussion, there's a bug which is triggered by adding a marker and setting zoom/position.

A fix is available in the latest `stable` branch (assuming you're using 0.7.3 today). If possible, try out latest and see if that solves the problem for you.

**Comment by melbourne2991** [comment]
I am using #8849980cd70fb70be6acac8f08ea9c7a1a5f11ee which is the latest commit on the stable branch?

**Comment by melbourne2991** [comment]
Still having the same problem with the stable branch i'm afraid

**Comment by perliedman** [comment]
@melbourne2991 ok, interesting. Would it somehow be possible to post code that reproduces the issue? Always hard to debug by just guessing from some code that you can't actually run.
