### ISSUE TITLE
Calling setView during a zoom animation freezes the map.

### ISSUE THREAD

**Issue by colllin** [Leaflet/Leaflet#3754]
Present in 1.0.0-beta.1...

Similar problem to what is described in #2021.

For now I can avoid it by disabling animations.  I'll look into it more when I have time and try to provide a jsfiddle.

**Comment by colllin** [comment]
For now my workaround is...

    setView(center, zoom, {
        animate: !map._animatingZoom
    })

**Comment by yohanboniface** [comment]
Can you set up a small test case to reproduce with latest master (using http://playground-leaflet.rhcloud.com/ just select "latest development version" in the "Add library" select)?

**Comment by saintsjd** [comment]
Here is a test case. 

http://playground-leaflet.rhcloud.com/jam/1/edit?html,console,output

Steps to reproduce the bug: 
Click the "Test (click me!)" button once

Expected behavior:
The map zoom level is 18

Result:
The map zoom level is usually 17.

Also try clicking the button again. Notice the behavior is different.

**Comment by yohanboniface** [comment]
Thanks. :)

**Comment by mourner** [comment]
Should be tested on `stable` branch as well — it might have been fixed by a recent commit...

**Comment by saintsjd** [comment]
Here is a test with stable branch. Behavior is different, but still does not work.

http://playground-leaflet.rhcloud.com/xob/1/edit?html,console,output

Steps to reproduce:
1. open the link above and click the TEST (click me!) button

Expected result:
The zoom level is 18.

Actual Result:
First time the button is clicked the zoom level is 17. Second time the zoom level is 18.

**Comment by IvanSanchez** [comment]
Due to playground maintenance, I messed up the existing examples, so the one for this bug now lives at http://playground-leaflet.rhcloud.com/hod/1/edit?html,output

**Comment by IvanSanchez** [comment]
I cannot reproduce in `master` anymore. Can anyone confirm?
