### ISSUE TITLE
Canvas renderer mouseover event precedence is incorrect when features have overlapping pixels

### ISSUE THREAD

**Issue by jbccollins** [Leaflet/Leaflet#5082]
## How to reproduce

- Leaflet version I'm using: 1.0.1
- Browser I'm using: Chrome
- OS/Platform I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing

I expect that when two features render with overlapping pixels (which does not necessarily mean overlapping geometries) the feature that renders on top will be the only feature to receive mouseover events. The default SVG renderer handles overlapping features in this way. The canvas renderer triggers mouseover events on all layers that contain the mouseover point. It's a bit hard to put into words so for the sake of brevity here are two gifs

SVG (expected):
![mouseover_correct](https://cloud.githubusercontent.com/assets/8915552/20155636/ca2da78c-a69a-11e6-88e9-abb7c872225e.gif)

Canvas: (unexpected)
![mouseover_bug](https://cloud.githubusercontent.com/assets/8915552/20155638/cbcae532-a69a-11e6-9dd1-509cac26d8d8.gif)

I believe that this was introduced (or at least made more apparent) by https://github.com/Leaflet/Leaflet/commit/609a79279272c88f1089bc2119d309b18c169110 which removes the break statement.

## Minimal example reproducing the issue
- A jsfiddle with a very simple example: http://jsfiddle.net/jcollin6/6k05szap/7/

## Possible solution

I would be willing to put up a PR for this but I don't know how. I tested these changes by directly modifying my local copy of leaflet.

```javascript
	_handleMouseHover: function(e, point) {
	    var id, layer, drawnLayerKeys;
            // reverse the keys so that we check layers from the top down 
	    drawnLayerKeys = Object.keys(this._drawnLayers).concat().reverse();
	    for (var i = 0; i < drawnLayerKeys.length; i++) {
	        id = drawnLayerKeys[i];
	        layer = this._drawnLayers[id];
	        if (layer.options.interactive && layer._containsPoint(point)) {
	            L.DomUtil.addClass(this._container, 'leaflet-interactive'); // change cursor
	            if (this._hoveredLayer && (this._hoveredLayer._leaflet_id.toString() !== id.toString())) {
                        // If we find a match but another layer is already 'hovered' 
                        // then trigger mouseout on that layer 
	                this._fireEvent([this._hoveredLayer], e, 'mouseout');
	            }
	            this._fireEvent([layer], e, 'mouseover');
	            this._hoveredLayer = layer;
                   // MUST break so that lower layer mouseover events are not triggered
	            break;
	        }
	    }

	    if (this._hoveredLayer) {
	        this._fireEvent([this._hoveredLayer], e);
	    }
	}
```

**Comment by jbccollins** [comment]
Looks like click events have a similar event propagation/precedence issue.

**Comment by IvanSanchez** [comment]
I recalled @perliedman working on the canvas path event firing in https://github.com/Leaflet/Leaflet/pull/5033 recently, so I must ask @jbccollins to test if this bug is reproducible using the latest `master` branch code.

(Hint: `https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js` and `https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet.css`)

**Comment by perliedman** [comment]
Yes, this sounds much like what was fixed in #5033, and related to #5028 and #4495. Please test with master, hopefully already fixed.

**Comment by jbccollins** [comment]
@IvanSanchez @perliedman Here is an updated fiddle with the js and css you provided. One of the bugs is fixed but other bugs still exists. https://jsfiddle.net/jcollin6/5ps5c43f/

1) Click events on the overlapping features still trigger clicks on both
2) The mouseout event is never triggered on the bottom feature when moving the cursor from the bottom feature to the top feature.

**Comment by balciseri** [comment]
```
_handleMouseHover: function (e, point) {
            var id, layer;
            for (id in this._drawnLayers) {
                layer = this._drawnLayers[id];
                if (layer.options.interactive && layer._containsPoint(point)) {
                    L.DomUtil.addClass(this._container, 'leaflet-interactive'); // change cursor
                    if (this._hoveredLayer && this._hoveredLayer !== layer) {
                        this._fireEvent([this._hoveredLayer], e, 'mouseout');
                    }
                    this._fireEvent([layer], e, 'mouseover');
                    this._hoveredLayer = layer;
                }
            }

            if (this._hoveredLayer) {
                this._fireEvent([this._hoveredLayer], e);
            }
        }
```
This is what i've been  using since https://github.com/Leaflet/Leaflet/issues/4495 , it's not great since it keeps firing the mouseout and mouseover events but at least in my app it's working because it's firing the mouseout events that really needed.
https://playground-leaflet.rhcloud.com/rix/edit?html,js,console,output

**Comment by jbccollins** [comment]
@perliedman @IvanSanchez Thanks for the quick turnaround on this guys! The hovering in my fiddle works great now!
