### ISSUE TITLE
Released JS in download ZIP has incorrect tag+commit reference

### ISSUE THREAD

**Issue by ghybs** [Leaflet/Leaflet#6062]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: N/A
- OS/Platform (with version) I'm using: N/A
- step 1: download the [`v1.3.1`](http://cdn.leafletjs.com/leaflet/v1.3.1/leaflet.zip) ZIP file from the official Leaflet [download page](http://leafletjs.com/download.html).
- step 2: extract the archive and inspect the content of the JS files (SRC and minified).

## What behaviour I'm expecting and which behaviour I'm seeing
- Expected: the tag+commit reference in the introductory comment/description should mention only `1.3.1` (i.e. release tag), and be absolutely identical to what is committed in the [`v1.3.1` release tag](https://github.com/Leaflet/Leaflet/releases/tag/v1.3.1) and published on [npm](https://www.npmjs.com/package/leaflet) (and accessible through [unpkg CDN](https://unpkg.com/leaflet@1.3.1/dist/)).
- Actual: the tag+commit reference is `1.3.1+Detached: ba6f97fff8647e724e4dfe66d2ed7da11f908989.ba6f97f`, the file having probably been automatically built _without_ the `NODE_ENV=release` environmental variable.

The only difference between the file in the downloadable ZIP and the one in the tag (which is identical in npm and unpkg) is the version reference in the introductory comment and in the `version` property (`"1.3.1+HEAD.ba6f97f"` v.s. expected `"1.3.1"`).

## Minimal example reproducing the issue

N/A

As mentioned at https://stackoverflow.com/questions/48832378/why-does-leaflet-js-1-3-1-differ-between-unpkg-com-and-leafletjs-com

**Comment by ghybs** [comment]
This discrepancy between JS file in downloadable ZIP and what is committed in tag appears to have existed since [`v1.0.0-rc.2`](https://github.com/Leaflet/Leaflet/releases/tag/v1.0.0-rc.2) inclusive, very probably introduced by PR https://github.com/Leaflet/Leaflet/pull/4455

I have no clue how assets are published in Leaflet CDN / S3 bucket, so I do not know how to check the publication and possibly fix this process.
This last part would also probably be related to issue https://github.com/Leaflet/Leaflet/issues/5999

**Comment by melato** [comment]
This is still happening in leaflet 1.4.0.

**Comment by melato** [comment]
Seems fixed in leaflet 1.5.1.

**Comment by Falke-Design** [comment]
@mourner this is not fixed for the zip 1.7.1 (the minified version is correct but not the the `-src` file), is this solved for the 1.8.0 release?

**Comment by mourner** [comment]
@Falke-Design pretty sure this will be fixed for the next release now that #7727 is merged. The detached head situation happened because the release script created an additional commit that added built files to git, which, as far as I remember, was introduced for the now-defunct Bower package manager.
