### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'wheel' event. 

### ISSUE THREAD

**Issue by JSanoja** [Leaflet/Leaflet#6881]
- [ x ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- init a map
- use 'wheel' event
![image](https://user-images.githubusercontent.com/6447596/68305133-e45a6080-0085-11ea-9c56-c52c4445c97e.png)

**Expected behavior**
Use pasive addEventListener { pasive : true }

**Current behavior**
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

  | addOne | @ | leaflet-src.js:2679
  | on | @ | leaflet-src.js:2616
  | addHooks | @ | leaflet-src.js:13609
  | enable | @ | leaflet-src.js:5734
  | addHandler | @ | leaflet-src.js:3739
  | init | @ | leaflet-src.js:385
  | proto.callInitHooks | @ | leaflet-src.js:357
  | initialize | @ | leaflet-src.js:3151
  | NewClass | @ | leaflet-src.js:301

**Environment**
- Leaflet version: 1.5.0
- Browser (with version): Version 78.0.3904.87 (Official Build) (64-bit)
- OS/Platform (with version): Ubuntu 19

**Additional context**
None

**Minimal example reproducing the issue**
none

**Comment by iamandrewluca** [comment]
This was fixed in https://github.com/Leaflet/Leaflet/pull/6694, there need to be a release.

**Comment by cherniavskii** [comment]
Released in 1.6.0

**Comment by bartoszwalicki** [comment]
Problem is still alive. I have Leaflet 1.6.0 in my project with conjunction with Angular and I still see in the console this:

![image](https://user-images.githubusercontent.com/46457719/86978510-66ec7000-c17f-11ea-9f3f-ae856cacbc0a.png)

**Comment by johnd0e** [comment]
Try latest `master`
