### ISSUE TITLE
Setting maxbounds on map creation throws warning

### ISSUE THREAD

**Issue by Makin-Things** [Leaflet/Leaflet#8173]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- create a map while setting maxbounds
- on loading the map it throws a warning
```
listener not found
_off @ leaflet.js:590
off @ leaflet.js:499
setMaxBounds @ leaflet.js:3422
initialize @ leaflet.js:3114
NewClass @ leaflet.js:302
createMap @ leaflet.js:4717
(anonymous) @ VM8861 about:srcdoc:231
```
**Expected behavior**

It should not throw a warning

**Current behavior**

**Environment**
- Leaflet version: 1.8.0 (the identical code with 1.7.1 doesn't throw a warning)
- Browser (with version): Latest Chrome and Firefox
- OS/Platform (with version): Windows 10

**Additional context**

**Minimal example reproducing the issue**
```
var map = new L.Map('leaflet', {
	layers: [
		new L.TileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			'attribution': 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
		})
	],
	center: [-35.149, 149.08013],
	maxBounds: [
		[0, 101.25],
		[-55.77657, 168.75],
	],
	zoom: 7
});
```

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by Falke-Design** [comment]
Thank you for reporting.
This should be fixed with #8168, so it would be nice if you can test it with the newest main version : https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/main/leaflet-src.js

**Comment by Makin-Things** [comment]
Thanks, I can confirm that the fix works for me. Closing.

**Comment by Darksymphony75** [comment]
is there a minimized version with this fix? I downloaded from the official page the 1.8-dev version, but still have this issue

**Comment by Falke-Design** [comment]
Try https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/main/leaflet-src.js

**Comment by Darksymphony75** [comment]
that§s what I talking about, I tried it already. It works fine alone, but with using Leaflet.Sleep the warning is there again.

**Comment by jonkoops** [comment]
Perhaps this plugin is overwriting existing functionality somehow? Could you log an issue on their repo?

It would also be useful for us if you could log this as a new issue instead, and make sure to provide a reproducible example (preferably something that can be viewed online).

**Comment by Darksymphony75** [comment]
I agree, but with the older version of Leaflet the same Leaflet.Sleep did not cause any warnings. For now I use the older version of Leaflet with Leaflet.Sleep and there is no warning at all. But I opened an issue for Leaflet.Sleep on their repo, however I don't think anyone will care there :)

**Comment by jonkoops** [comment]
This indeed might be considered a breaking change. Although one could argue it's silly to use the API in this manner.
